version: '3.8'

services:
  # MeiliSearch
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: easymeili-meilisearch
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=your_master_key_here
      - MEILI_ENV=development
    volumes:
      - meili_data:/meili_data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7700/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # EasyMeili Application
  easymeili:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: easymeili-app
    ports:
      - "3000:3000"
    environment:
      - MEILISEARCH_HOST=http://meilisearch:7700
      - MEILISEARCH_KEY=your_master_key_here
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
    depends_on:
      meilisearch:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  meili_data:
    driver: local 